{% set name = "jupyterlab-chat" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
    sha256: ba6f636a62499abd02c5ac8d714ebfbab612fbf1d391e99c2952bad4b55a5941

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install .  --no-deps -vv --no-build-isolation --ignore-installed --no-index

requirements:
  host:
    - python
    - hatchling >=1.5.0
    - hatch-jupyter-builder >=0.5
    - jupyterlab >=4.0.0,<5
    - pip
  run:
    - python
    - jupyter-collaboration >=4,<5
    - jupyter_server >=2.0.1,<3
    - jupyter_ydoc >=3.0.0,<4
    - pycrdt >=0.12.48,<0.13.0

test:
  imports:
    - jupyterlab_chat
  requires:
    - python
    - jupyterlab >=4.0,<5
    - ripgrep
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - jupyter labextension list 2>&1 | rg -ie "jupyterlab-chat-extension.*OK"  # [unix]
    - jupyter labextension list 2>&1 | findstr /r /i "jupyterlab-chat-extension.*OK"  # [unix]

about:
  summary: A chat extension based on shared documents
  homepage: https://github.com/jupyterlab/jupyter-chat/
  repository: https://github.com/jupyterlab/jupyter-chat/
  documentation: https://jupyter-chat.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - brichet
    - jtpio
